### ISSUE TITLE
PER-1 compatibility

### ISSUE THREAD

**Issue by edsrzf** [pmjones/php-styler#3]
I think it's great that php-styler is opinionated about styling, but I think its opinion should be compatible with [PER-1](https://www.php-fig.org/per/coding-style/). Incompatibility seems like a pretty large barrier to community adoption.

It's not clear whether this is currently a project goal or not. I think it'd be good to make that clear in the README, one way or the other.

Some examples of incompatibilities:
* Space before the colon on function return types: `function foo() : void {}`. PER-1 states ["The colon and declaration MUST be on the same line as the argument list closing parenthesis with **no spaces between the two characters**"](https://www.php-fig.org/per/coding-style/#45-method-and-function-parameters)
* Space before post-increment operator: `$i ++`. PER-1 states ["The increment/decrement operators MUST NOT have any space between the operator and operand"](https://www.php-fig.org/per/coding-style/#61-unary-operators)

**Comment by pmjones** [comment]
PSR-2/PSR-12/PER-1 compatibility in the default Styler is not one of the project goals, in the same way that (e.g.) Symfony/Doctrine/Cake/Laravel/Nette/etc. compatibility is not one of the project goals.

Having said that, programmability of the Styler *is* a goal, so FIG (and the other projects) are welcome to publish a Styler customized to their own preferences -- and if some aspect of the project makes that difficult, I will do what I can to remedy it.

**Comment by pmjones** [comment]
@edsrzf If you are still interested, the [README-CUSTOM.md](https://github.com/pmjones/php-styler/blob/0.x/README-CUSTOM.md) document should help guide you in building a _Styler_ customized to PSR/PER/whatever-you-like.

I am interested to hear how that goes, if you decide to pursue it!

**Comment by paulshryock** [comment]
> [PER-1](https://www.php-fig.org/per/coding-style/) incompatibility seems like a pretty large barrier to community adoption.

100%.
